apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: webstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:10.11
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-creds
              key: dbpass
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mariadb-creds
              key: dbname
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mariadb-creds
              key: dbuser
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-creds
              key: dbpass
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mariadb-data
          mountPath: /var/lib/mysql
      volumes:
      - name: mariadb-data
        persistentVolumeClaim:
          claimName: mariadb-pvc
